# Generated by Django 5.0.7 on 2025-04-27 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.AddField(
            model_name='student',
            name='last_name',
            field=models.CharField(default='Azganun', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(default='Anun', max_length=100),
        ),
    ]
